export const animalCategories = [
  "all",
  "mammal",
  "bird",
  "reptile",
  "ocean",
  "bug",
  "fantasy",
] as const;
export type AnimalCategory = Exclude<(typeof animalCategories)[number], "all">;
export interface Animal {
  id: string;
  name: string;
  nameEn: string;
  emoji: string;
  category: AnimalCategory;
}

// Copyright © 1991-2026 Unicode, Inc. Unicode and the Unicode Logo are registered
// trademarks of Unicode, Inc. in the U.S. and other countries.
// Terms: https://www.unicode.org/terms_of_use.html
// Source: Unicode Emoji 18.0, https://unicode.org/Public/18.0.0/emoji/emoji-test.txt
// Unicode data license: https://www.unicode.org/license.txt (see ../licenses/UNICODE.txt)
// Fully-qualified entries from every animal-* subgroup of Animals & Nature.
// Also includes all 12 cat-face / monkey-face expressions from Smileys & Emotion.
// Animal traces appear as fantasy sprites; plants and qualification variants are excluded.
export const animalCatalogSource = {
  version: "18.0",
  url: "https://unicode.org/Public/18.0.0/emoji/emoji-test.txt",
  animalSubgroupCount: 132,
  expressionCount: 12,
  count: 144,
} as const;
export const animals: Animal[] = [
  {
    id: "monkey-face",
    name: "猴脸",
    nameEn: "monkey face",
    emoji: "🐵",
    category: "mammal",
  },
  {
    id: "monkey",
    name: "猴子",
    nameEn: "monkey",
    emoji: "🐒",
    category: "mammal",
  },
  {
    id: "gorilla",
    name: "大猩猩",
    nameEn: "gorilla",
    emoji: "🦍",
    category: "mammal",
  },
  {
    id: "orangutan",
    name: "红毛猩猩",
    nameEn: "orangutan",
    emoji: "🦧",
    category: "mammal",
  },
  {
    id: "dog-face",
    name: "狗脸",
    nameEn: "dog face",
    emoji: "🐶",
    category: "mammal",
  },
  {
    id: "dog",
    name: "小狗",
    nameEn: "dog",
    emoji: "🐕",
    category: "mammal",
  },
  {
    id: "guide-dog",
    name: "导盲犬",
    nameEn: "guide dog",
    emoji: "🦮",
    category: "mammal",
  },
  {
    id: "service-dog",
    name: "服务犬",
    nameEn: "service dog",
    emoji: "🐕‍🦺",
    category: "mammal",
  },
  {
    id: "poodle",
    name: "贵宾犬",
    nameEn: "poodle",
    emoji: "🐩",
    category: "mammal",
  },
  {
    id: "wolf",
    name: "狼",
    nameEn: "wolf",
    emoji: "🐺",
    category: "mammal",
  },
  {
    id: "fox",
    name: "狐狸",
    nameEn: "fox",
    emoji: "🦊",
    category: "mammal",
  },
  {
    id: "raccoon",
    name: "浣熊",
    nameEn: "raccoon",
    emoji: "🦝",
    category: "mammal",
  },
  {
    id: "cat-face",
    name: "猫脸",
    nameEn: "cat face",
    emoji: "🐱",
    category: "mammal",
  },
  {
    id: "cat",
    name: "小猫",
    nameEn: "cat",
    emoji: "🐈",
    category: "mammal",
  },
  {
    id: "black-cat",
    name: "黑猫",
    nameEn: "black cat",
    emoji: "🐈‍⬛",
    category: "mammal",
  },
  {
    id: "lion",
    name: "狮子",
    nameEn: "lion",
    emoji: "🦁",
    category: "mammal",
  },
  {
    id: "tiger-face",
    name: "虎脸",
    nameEn: "tiger face",
    emoji: "🐯",
    category: "mammal",
  },
  {
    id: "tiger",
    name: "老虎",
    nameEn: "tiger",
    emoji: "🐅",
    category: "mammal",
  },
  {
    id: "leopard",
    name: "花豹",
    nameEn: "leopard",
    emoji: "🐆",
    category: "mammal",
  },
  {
    id: "horse-face",
    name: "马脸",
    nameEn: "horse face",
    emoji: "🐴",
    category: "mammal",
  },
  {
    id: "moose",
    name: "驼鹿",
    nameEn: "moose",
    emoji: "🫎",
    category: "mammal",
  },
  {
    id: "donkey",
    name: "毛驴",
    nameEn: "donkey",
    emoji: "🫏",
    category: "mammal",
  },
  {
    id: "horse",
    name: "骏马",
    nameEn: "horse",
    emoji: "🐎",
    category: "mammal",
  },
  {
    id: "unicorn",
    name: "独角兽",
    nameEn: "unicorn",
    emoji: "🦄",
    category: "fantasy",
  },
  {
    id: "zebra",
    name: "斑马",
    nameEn: "zebra",
    emoji: "🦓",
    category: "mammal",
  },
  {
    id: "deer",
    name: "小鹿",
    nameEn: "deer",
    emoji: "🦌",
    category: "mammal",
  },
  {
    id: "bison",
    name: "野牛",
    nameEn: "bison",
    emoji: "🦬",
    category: "mammal",
  },
  {
    id: "cow-face",
    name: "牛脸",
    nameEn: "cow face",
    emoji: "🐮",
    category: "mammal",
  },
  {
    id: "ox",
    name: "公牛",
    nameEn: "ox",
    emoji: "🐂",
    category: "mammal",
  },
  {
    id: "water-buffalo",
    name: "水牛",
    nameEn: "water buffalo",
    emoji: "🐃",
    category: "mammal",
  },
  {
    id: "cow",
    name: "奶牛",
    nameEn: "cow",
    emoji: "🐄",
    category: "mammal",
  },
  {
    id: "pig-face",
    name: "猪脸",
    nameEn: "pig face",
    emoji: "🐷",
    category: "mammal",
  },
  {
    id: "pig",
    name: "小猪",
    nameEn: "pig",
    emoji: "🐖",
    category: "mammal",
  },
  {
    id: "boar",
    name: "野猪",
    nameEn: "boar",
    emoji: "🐗",
    category: "mammal",
  },
  {
    id: "pig-nose",
    name: "猪鼻子",
    nameEn: "pig nose",
    emoji: "🐽",
    category: "mammal",
  },
  {
    id: "ram",
    name: "公绵羊",
    nameEn: "ram",
    emoji: "🐏",
    category: "mammal",
  },
  {
    id: "ewe",
    name: "母绵羊",
    nameEn: "ewe",
    emoji: "🐑",
    category: "mammal",
  },
  {
    id: "goat",
    name: "山羊",
    nameEn: "goat",
    emoji: "🐐",
    category: "mammal",
  },
  {
    id: "camel",
    name: "单峰驼",
    nameEn: "camel",
    emoji: "🐪",
    category: "mammal",
  },
  {
    id: "two-hump-camel",
    name: "双峰驼",
    nameEn: "two-hump camel",
    emoji: "🐫",
    category: "mammal",
  },
  {
    id: "llama",
    name: "美洲驼",
    nameEn: "llama",
    emoji: "🦙",
    category: "mammal",
  },
  {
    id: "giraffe",
    name: "长颈鹿",
    nameEn: "giraffe",
    emoji: "🦒",
    category: "mammal",
  },
  {
    id: "elephant",
    name: "大象",
    nameEn: "elephant",
    emoji: "🐘",
    category: "mammal",
  },
  {
    id: "mammoth",
    name: "猛犸象",
    nameEn: "mammoth",
    emoji: "🦣",
    category: "mammal",
  },
  {
    id: "rhinoceros",
    name: "犀牛",
    nameEn: "rhinoceros",
    emoji: "🦏",
    category: "mammal",
  },
  {
    id: "hippopotamus",
    name: "河马",
    nameEn: "hippopotamus",
    emoji: "🦛",
    category: "mammal",
  },
  {
    id: "mouse-face",
    name: "鼠脸",
    nameEn: "mouse face",
    emoji: "🐭",
    category: "mammal",
  },
  {
    id: "mouse",
    name: "小鼠",
    nameEn: "mouse",
    emoji: "🐁",
    category: "mammal",
  },
  {
    id: "rat",
    name: "大老鼠",
    nameEn: "rat",
    emoji: "🐀",
    category: "mammal",
  },
  {
    id: "hamster",
    name: "仓鼠",
    nameEn: "hamster",
    emoji: "🐹",
    category: "mammal",
  },
  {
    id: "rabbit-face",
    name: "兔脸",
    nameEn: "rabbit face",
    emoji: "🐰",
    category: "mammal",
  },
  {
    id: "rabbit",
    name: "兔子",
    nameEn: "rabbit",
    emoji: "🐇",
    category: "mammal",
  },
  {
    id: "chipmunk",
    name: "花栗鼠",
    nameEn: "chipmunk",
    emoji: "🐿️",
    category: "mammal",
  },
  {
    id: "beaver",
    name: "河狸",
    nameEn: "beaver",
    emoji: "🦫",
    category: "mammal",
  },
  {
    id: "hedgehog",
    name: "刺猬",
    nameEn: "hedgehog",
    emoji: "🦔",
    category: "mammal",
  },
  {
    id: "bat",
    name: "蝙蝠",
    nameEn: "bat",
    emoji: "🦇",
    category: "mammal",
  },
  {
    id: "bear",
    name: "棕熊",
    nameEn: "bear",
    emoji: "🐻",
    category: "mammal",
  },
  {
    id: "polar-bear",
    name: "北极熊",
    nameEn: "polar bear",
    emoji: "🐻‍❄️",
    category: "mammal",
  },
  {
    id: "koala",
    name: "考拉",
    nameEn: "koala",
    emoji: "🐨",
    category: "mammal",
  },
  {
    id: "panda",
    name: "熊猫",
    nameEn: "panda",
    emoji: "🐼",
    category: "mammal",
  },
  {
    id: "sloth",
    name: "树懒",
    nameEn: "sloth",
    emoji: "🦥",
    category: "mammal",
  },
  {
    id: "otter",
    name: "水獭",
    nameEn: "otter",
    emoji: "🦦",
    category: "mammal",
  },
  {
    id: "skunk",
    name: "臭鼬",
    nameEn: "skunk",
    emoji: "🦨",
    category: "mammal",
  },
  {
    id: "kangaroo",
    name: "袋鼠",
    nameEn: "kangaroo",
    emoji: "🦘",
    category: "mammal",
  },
  {
    id: "badger",
    name: "獾",
    nameEn: "badger",
    emoji: "🦡",
    category: "mammal",
  },
  {
    id: "paw-prints",
    name: "爪印精灵",
    nameEn: "paw prints sprite",
    emoji: "🐾",
    category: "fantasy",
  },
  {
    id: "turkey",
    name: "火鸡",
    nameEn: "turkey",
    emoji: "🦃",
    category: "bird",
  },
  {
    id: "chicken",
    name: "母鸡",
    nameEn: "chicken",
    emoji: "🐔",
    category: "bird",
  },
  {
    id: "rooster",
    name: "公鸡",
    nameEn: "rooster",
    emoji: "🐓",
    category: "bird",
  },
  {
    id: "hatching-chick",
    name: "破壳小鸡",
    nameEn: "hatching chick",
    emoji: "🐣",
    category: "bird",
  },
  {
    id: "baby-chick",
    name: "小鸡",
    nameEn: "baby chick",
    emoji: "🐤",
    category: "bird",
  },
  {
    id: "front-facing-baby-chick",
    name: "正面小鸡",
    nameEn: "front-facing baby chick",
    emoji: "🐥",
    category: "bird",
  },
  {
    id: "bird",
    name: "小鸟",
    nameEn: "bird",
    emoji: "🐦",
    category: "bird",
  },
  {
    id: "penguin",
    name: "企鹅",
    nameEn: "penguin",
    emoji: "🐧",
    category: "bird",
  },
  {
    id: "dove",
    name: "鸽子",
    nameEn: "dove",
    emoji: "🕊️",
    category: "bird",
  },
  {
    id: "eagle",
    name: "老鹰",
    nameEn: "eagle",
    emoji: "🦅",
    category: "bird",
  },
  {
    id: "duck",
    name: "鸭子",
    nameEn: "duck",
    emoji: "🦆",
    category: "bird",
  },
  {
    id: "swan",
    name: "天鹅",
    nameEn: "swan",
    emoji: "🦢",
    category: "bird",
  },
  {
    id: "owl",
    name: "猫头鹰",
    nameEn: "owl",
    emoji: "🦉",
    category: "bird",
  },
  {
    id: "dodo",
    name: "渡渡鸟",
    nameEn: "dodo",
    emoji: "🦤",
    category: "bird",
  },
  {
    id: "feather",
    name: "羽毛精灵",
    nameEn: "feather sprite",
    emoji: "🪶",
    category: "bird",
  },
  {
    id: "flamingo",
    name: "火烈鸟",
    nameEn: "flamingo",
    emoji: "🦩",
    category: "bird",
  },
  {
    id: "peacock",
    name: "孔雀",
    nameEn: "peacock",
    emoji: "🦚",
    category: "bird",
  },
  {
    id: "parrot",
    name: "鹦鹉",
    nameEn: "parrot",
    emoji: "🦜",
    category: "bird",
  },
  {
    id: "wing",
    name: "翅膀精灵",
    nameEn: "wing sprite",
    emoji: "🪽",
    category: "bird",
  },
  {
    id: "black-bird",
    name: "黑鸟",
    nameEn: "black bird",
    emoji: "🐦‍⬛",
    category: "bird",
  },
  {
    id: "goose",
    name: "大鹅",
    nameEn: "goose",
    emoji: "🪿",
    category: "bird",
  },
  {
    id: "phoenix",
    name: "凤凰",
    nameEn: "phoenix",
    emoji: "🐦‍🔥",
    category: "fantasy",
  },
  {
    id: "frog",
    name: "青蛙",
    nameEn: "frog",
    emoji: "🐸",
    category: "reptile",
  },
  {
    id: "crocodile",
    name: "鳄鱼",
    nameEn: "crocodile",
    emoji: "🐊",
    category: "reptile",
  },
  {
    id: "turtle",
    name: "乌龟",
    nameEn: "turtle",
    emoji: "🐢",
    category: "reptile",
  },
  {
    id: "lizard",
    name: "蜥蜴",
    nameEn: "lizard",
    emoji: "🦎",
    category: "reptile",
  },
  {
    id: "snake",
    name: "蛇",
    nameEn: "snake",
    emoji: "🐍",
    category: "reptile",
  },
  {
    id: "dragon-face",
    name: "龙脸",
    nameEn: "dragon face",
    emoji: "🐲",
    category: "fantasy",
  },
  {
    id: "dragon",
    name: "龙",
    nameEn: "dragon",
    emoji: "🐉",
    category: "fantasy",
  },
  {
    id: "sauropod",
    name: "蜥脚恐龙",
    nameEn: "sauropod",
    emoji: "🦕",
    category: "reptile",
  },
  {
    id: "t-rex",
    name: "霸王龙",
    nameEn: "T-Rex",
    emoji: "🦖",
    category: "reptile",
  },
  {
    id: "spouting-whale",
    name: "喷水鲸",
    nameEn: "spouting whale",
    emoji: "🐳",
    category: "ocean",
  },
  {
    id: "whale",
    name: "鲸鱼",
    nameEn: "whale",
    emoji: "🐋",
    category: "ocean",
  },
  {
    id: "dolphin",
    name: "海豚",
    nameEn: "dolphin",
    emoji: "🐬",
    category: "ocean",
  },
  {
    id: "orca",
    name: "虎鲸",
    nameEn: "orca",
    emoji: "🫍",
    category: "ocean",
  },
  {
    id: "seal",
    name: "海豹",
    nameEn: "seal",
    emoji: "🦭",
    category: "ocean",
  },
  {
    id: "fish",
    name: "小鱼",
    nameEn: "fish",
    emoji: "🐟",
    category: "ocean",
  },
  {
    id: "tropical-fish",
    name: "热带鱼",
    nameEn: "tropical fish",
    emoji: "🐠",
    category: "ocean",
  },
  {
    id: "blowfish",
    name: "河豚",
    nameEn: "blowfish",
    emoji: "🐡",
    category: "ocean",
  },
  {
    id: "shark",
    name: "鲨鱼",
    nameEn: "shark",
    emoji: "🦈",
    category: "ocean",
  },
  {
    id: "octopus",
    name: "章鱼",
    nameEn: "octopus",
    emoji: "🐙",
    category: "ocean",
  },
  {
    id: "spiral-shell",
    name: "海螺",
    nameEn: "spiral shell",
    emoji: "🐚",
    category: "ocean",
  },
  {
    id: "coral",
    name: "珊瑚",
    nameEn: "coral",
    emoji: "🪸",
    category: "ocean",
  },
  {
    id: "jellyfish",
    name: "水母",
    nameEn: "jellyfish",
    emoji: "🪼",
    category: "ocean",
  },
  {
    id: "crab",
    name: "螃蟹",
    nameEn: "crab",
    emoji: "🦀",
    category: "ocean",
  },
  {
    id: "lobster",
    name: "龙虾",
    nameEn: "lobster",
    emoji: "🦞",
    category: "ocean",
  },
  {
    id: "shrimp",
    name: "虾",
    nameEn: "shrimp",
    emoji: "🦐",
    category: "ocean",
  },
  {
    id: "squid",
    name: "鱿鱼",
    nameEn: "squid",
    emoji: "🦑",
    category: "ocean",
  },
  {
    id: "oyster",
    name: "牡蛎",
    nameEn: "oyster",
    emoji: "🦪",
    category: "ocean",
  },
  {
    id: "snail",
    name: "蜗牛",
    nameEn: "snail",
    emoji: "🐌",
    category: "bug",
  },
  {
    id: "butterfly",
    name: "蝴蝶",
    nameEn: "butterfly",
    emoji: "🦋",
    category: "bug",
  },
  {
    id: "monarch-butterfly",
    name: "帝王蝶",
    nameEn: "monarch butterfly",
    emoji: "🫌",
    category: "bug",
  },
  {
    id: "bug",
    name: "毛毛虫",
    nameEn: "bug",
    emoji: "🐛",
    category: "bug",
  },
  {
    id: "ant",
    name: "蚂蚁",
    nameEn: "ant",
    emoji: "🐜",
    category: "bug",
  },
  {
    id: "honeybee",
    name: "蜜蜂",
    nameEn: "honeybee",
    emoji: "🐝",
    category: "bug",
  },
  {
    id: "beetle",
    name: "甲虫",
    nameEn: "beetle",
    emoji: "🪲",
    category: "bug",
  },
  {
    id: "lady-beetle",
    name: "瓢虫",
    nameEn: "lady beetle",
    emoji: "🐞",
    category: "bug",
  },
  {
    id: "cricket",
    name: "蟋蟀",
    nameEn: "cricket",
    emoji: "🦗",
    category: "bug",
  },
  {
    id: "cockroach",
    name: "蟑螂",
    nameEn: "cockroach",
    emoji: "🪳",
    category: "bug",
  },
  {
    id: "spider",
    name: "蜘蛛",
    nameEn: "spider",
    emoji: "🕷️",
    category: "bug",
  },
  {
    id: "spider-web",
    name: "蜘蛛网精灵",
    nameEn: "spider web sprite",
    emoji: "🕸️",
    category: "fantasy",
  },
  {
    id: "scorpion",
    name: "蝎子",
    nameEn: "scorpion",
    emoji: "🦂",
    category: "bug",
  },
  {
    id: "mosquito",
    name: "蚊子",
    nameEn: "mosquito",
    emoji: "🦟",
    category: "bug",
  },
  {
    id: "fly",
    name: "苍蝇",
    nameEn: "fly",
    emoji: "🪰",
    category: "bug",
  },
  {
    id: "worm",
    name: "蚯蚓",
    nameEn: "worm",
    emoji: "🪱",
    category: "bug",
  },
  {
    id: "microbe",
    name: "微生物",
    nameEn: "microbe",
    emoji: "🦠",
    category: "bug",
  },
  {
    id: "grinning-cat",
    name: "笑脸猫",
    nameEn: "grinning cat",
    emoji: "😺",
    category: "mammal",
  },
  {
    id: "grinning-cat-with-smiling-eyes",
    name: "眯眼笑猫",
    nameEn: "grinning cat with smiling eyes",
    emoji: "😸",
    category: "mammal",
  },
  {
    id: "cat-with-tears-of-joy",
    name: "笑哭猫",
    nameEn: "cat with tears of joy",
    emoji: "😹",
    category: "mammal",
  },
  {
    id: "smiling-cat-with-heart-eyes",
    name: "爱心眼猫",
    nameEn: "smiling cat with heart-eyes",
    emoji: "😻",
    category: "mammal",
  },
  {
    id: "cat-with-wry-smile",
    name: "坏笑猫",
    nameEn: "cat with wry smile",
    emoji: "😼",
    category: "mammal",
  },
  {
    id: "kissing-cat",
    name: "亲亲猫",
    nameEn: "kissing cat",
    emoji: "😽",
    category: "mammal",
  },
  {
    id: "weary-cat",
    name: "惊讶猫",
    nameEn: "weary cat",
    emoji: "🙀",
    category: "mammal",
  },
  {
    id: "crying-cat",
    name: "哭泣猫",
    nameEn: "crying cat",
    emoji: "😿",
    category: "mammal",
  },
  {
    id: "pouting-cat",
    name: "生气猫",
    nameEn: "pouting cat",
    emoji: "😾",
    category: "mammal",
  },
  {
    id: "see-no-evil-monkey",
    name: "捂眼猴",
    nameEn: "see-no-evil monkey",
    emoji: "🙈",
    category: "mammal",
  },
  {
    id: "hear-no-evil-monkey",
    name: "捂耳猴",
    nameEn: "hear-no-evil monkey",
    emoji: "🙉",
    category: "mammal",
  },
  {
    id: "speak-no-evil-monkey",
    name: "捂嘴猴",
    nameEn: "speak-no-evil monkey",
    emoji: "🙊",
    category: "mammal",
  },
];
