export interface Dish {
  id: string;
  name: string;
  cuisine: string;
  description: string;
  ingredients: string[];
  emoji: string;
  color: string;
  nameEn: string;
  cuisineEn: string;
  descriptionEn: string;
  ingredientsEn: string[];
}
export const cuisines = [
  "全部",
  "中式",
  "日式",
  "韩式",
  "意式",
  "法式",
  "东南亚",
  "美式",
];
const ingredientEnglish: Record<string, string> = {
  egg: "Egg",
  rice: "Rice",
  tomato: "Tomato",
  chicken: "Chicken",
  beef: "Beef",
  pork: "Pork",
  shrimp: "Shrimp",
  salmon: "Salmon",
  noodle: "Noodles",
  flour: "Flour",
  cheese: "Cheese",
  milk: "Milk",
  potato: "Potato",
  mushroom: "Mushroom",
  tofu: "Tofu",
  chili: "Chili",
  onion: "Onion",
  coconut: "Coconut milk",
  strawberry: "Strawberry",
  butter: "Butter",
  durian: "Durian",
  "stinky-tofu": "Stinky tofu",
  "century-egg": "Century egg",
  chocolate: "Chocolate",
  "carrot": "Carrot",
  "broccoli": "Broccoli",
  "cabbage": "Cabbage",
  "cucumber": "Cucumber",
  "corn": "Corn",
  "pumpkin": "Pumpkin",
  "spinach": "Spinach",
  "eggplant": "Eggplant",
  "duck": "Duck",
  "bacon": "Bacon",
  "sausage": "Sausage",
  "squid": "Squid",
  "crab": "Crab",
  "clam": "Clams",
  "yogurt": "Yogurt",
  "cream": "Cream",
  "condensed-milk": "Condensed milk",
  "bread": "Bread",
  "pasta": "Pasta",
  "oats": "Oats",
  "rice-cake": "Rice cakes",
  "banana": "Banana",
  "apple": "Apple",
  "lemon": "Lemon",
  "mango": "Mango",
  "pineapple": "Pineapple",
  "blueberry": "Blueberries",
  "watermelon": "Watermelon",
  "salt": "Sea salt",
  "sugar": "Sugar",
  "soy-sauce": "Soy sauce",
  "vinegar": "Vinegar",
  "honey": "Honey",
  "coffee": "Coffee",
  "mustard": "Mustard",
  "chili-oil": "Chili oil",
  moon: "Moonlight icing",
  stardust: "Stardust",
  rainbow: "Rainbow dew",
  dragon: "Dragonfire chili",
  cloud: "Cloud cream",
  fairy: "Fairy mint",
  comet: "Comet popping candy",
  crystal: "Amethyst salt",
};
export const ingredientCategories = ["all", "vegetables", "protein", "dairy", "staples", "fruit", "seasoning"] as const;
export type IngredientCategory = typeof ingredientCategories[number];
const categoryMembers:Record<string,string[]> = {
  vegetables: "tomato potato mushroom chili onion carrot broccoli cabbage cucumber corn pumpkin spinach eggplant".split(" "),
  protein: "chicken beef pork shrimp salmon tofu stinky-tofu duck bacon sausage squid crab clam".split(" "),
  dairy: "egg cheese milk butter century-egg yogurt cream condensed-milk".split(" "),
  staples: "rice noodle flour bread pasta oats rice-cake".split(" "),
  fruit: "strawberry durian banana apple lemon mango pineapple blueberry watermelon".split(" "),
  seasoning: "coconut chocolate salt sugar soy-sauce vinegar honey coffee mustard chili-oil".split(" "),
};
export type IngredientArtKind = "leaf" | "root" | "mushroom" | "pod" | "meat" | "fish" | "shell" | "cube" | "grain" | "fruit" | "bottle" | "jar" | "herb" | "spice";
export interface Ingredient {
  id: string;
  name: string;
  nameEn: string;
  kind: "real" | "magic";
  category: IngredientCategory;
  emoji: string;
  art?: IngredientArtKind;
}
const originalIngredients: Ingredient[] = [
  ["egg", "鸡蛋", "real", "🥚"],
  ["rice", "米饭", "real", "🍚"],
  ["tomato", "番茄", "real", "🍅"],
  ["chicken", "鸡肉", "real", "🍗"],
  ["beef", "牛肉", "real", "🥩"],
  ["pork", "猪肉", "real", "🥓"],
  ["shrimp", "鲜虾", "real", "🦐"],
  ["salmon", "三文鱼", "real", "🐟"],
  ["noodle", "面条", "real", "🍜"],
  ["flour", "面粉", "real", "🌾"],
  ["cheese", "芝士", "real", "🧀"],
  ["milk", "牛奶", "real", "🥛"],
  ["potato", "土豆", "real", "🥔"],
  ["mushroom", "蘑菇", "real", "🍄"],
  ["tofu", "豆腐", "real", "🧊"],
  ["chili", "辣椒", "real", "🌶️"],
  ["onion", "洋葱", "real", "🧅"],
  ["coconut", "椰奶", "real", "🥥"],
  ["strawberry", "草莓", "real", "🍓"],
  ["butter", "黄油", "real", "🧈"],
  ["durian", "榴莲", "real", "🍈"],
  ["stinky-tofu", "臭豆腐", "real", "🧊"],
  ["century-egg", "皮蛋", "real", "🥚"],
  ["chocolate", "巧克力", "real", "🍫"],
  ["carrot", "胡萝卜", "real", "🥕"],
  ["broccoli", "西兰花", "real", "🥦"],
  ["cabbage", "卷心菜", "real", "🥬"],
  ["cucumber", "黄瓜", "real", "🥒"],
  ["corn", "玉米", "real", "🌽"],
  ["pumpkin", "南瓜", "real", "🎃"],
  ["spinach", "菠菜", "real", "🥬"],
  ["eggplant", "茄子", "real", "🍆"],
  ["duck", "鸭肉", "real", "🍗"],
  ["bacon", "培根", "real", "🥓"],
  ["sausage", "香肠", "real", "🌭"],
  ["squid", "鱿鱼", "real", "🦑"],
  ["crab", "螃蟹", "real", "🦀"],
  ["clam", "蛤蜊", "real", "🐚"],
  ["yogurt", "酸奶", "real", "🥛"],
  ["cream", "奶油", "real", "🥛"],
  ["condensed-milk", "炼乳", "real", "🥛"],
  ["bread", "面包", "real", "🍞"],
  ["pasta", "意大利面", "real", "🍝"],
  ["oats", "燕麦", "real", "🌾"],
  ["rice-cake", "年糕", "real", "🍘"],
  ["banana", "香蕉", "real", "🍌"],
  ["apple", "苹果", "real", "🍎"],
  ["lemon", "柠檬", "real", "🍋"],
  ["mango", "芒果", "real", "🥭"],
  ["pineapple", "菠萝", "real", "🍍"],
  ["blueberry", "蓝莓", "real", "🫐"],
  ["watermelon", "西瓜", "real", "🍉"],
  ["salt", "海盐", "real", "🧂"],
  ["sugar", "白糖", "real", "🍬"],
  ["soy-sauce", "酱油", "real", "🍶"],
  ["vinegar", "醋", "real", "🍶"],
  ["honey", "蜂蜜", "real", "🍯"],
  ["coffee", "咖啡", "real", "☕"],
  ["mustard", "芥末", "real", "🌱"],
  ["chili-oil", "辣椒油", "real", "🌶️"],
  ["moon", "月光糖霜", "magic", "🌙"],
  ["stardust", "星星碎屑", "magic", "✨"],
  ["rainbow", "彩虹露珠", "magic", "🌈"],
  ["dragon", "龙息辣椒", "magic", "🔥"],
  ["cloud", "云朵奶油", "magic", "☁️"],
  ["fairy", "精灵薄荷", "magic", "🌿"],
  ["comet", "彗星跳跳糖", "magic", "💫"],
  ["crystal", "紫水晶盐", "magic", "🔮"],
].map(([id, name, kind, emoji]) => ({
  id: id!,
  name: name!,
  nameEn: ingredientEnglish[id!]!,
  kind: kind as "real" | "magic",
  category: (Object.entries(categoryMembers).find(([,ids])=>ids.includes(id!))?.[0] || "all") as IngredientCategory,
  emoji: emoji!,
}));
// Ingredient names only: CookLikeHOC's 葱油/蒜蓉酱/鱼香风味酱/麻婆豆腐料
// informed the Chinese sauce ingredients; the remaining pantry items are general food facts.
// Reference revision: 0999f83f0eace270812dec806236b27b2290f466 (no recipe text copied).
const expandedIngredients: [string, string, string, Exclude<IngredientCategory, "all">, string, IngredientArtKind][] = [
  ["bok-choy", "小白菜", "Bok choy", "vegetables", "🥬", "leaf"],
  ["napa-cabbage", "大白菜", "Napa cabbage", "vegetables", "🥬", "leaf"],
  ["lettuce", "生菜", "Lettuce", "vegetables", "🥬", "leaf"],
  ["celery", "芹菜", "Celery", "vegetables", "🥬", "leaf"],
  ["water-spinach", "空心菜", "Water spinach", "vegetables", "🥬", "leaf"],
  ["chinese-chives", "韭菜", "Chinese chives", "vegetables", "🥬", "leaf"],
  ["mustard-greens", "芥菜", "Mustard greens", "vegetables", "🥬", "leaf"],
  ["pea-shoots", "豌豆苗", "Pea shoots", "vegetables", "🥬", "leaf"],
  ["amaranth", "苋菜", "Amaranth greens", "vegetables", "🥬", "leaf"],
  ["kale", "羽衣甘蓝", "Kale", "vegetables", "🥬", "leaf"],
  ["daikon", "白萝卜", "Daikon", "vegetables", "🥕", "root"],
  ["lotus-root", "莲藕", "Lotus root", "vegetables", "🥕", "root"],
  ["sweet-potato", "红薯", "Sweet potato", "vegetables", "🥕", "root"],
  ["taro", "芋头", "Taro", "vegetables", "🥕", "root"],
  ["chinese-yam", "山药", "Chinese yam", "vegetables", "🥕", "root"],
  ["beetroot", "甜菜根", "Beetroot", "vegetables", "🥕", "root"],
  ["bamboo-shoots", "竹笋", "Bamboo shoots", "vegetables", "🥕", "root"],
  ["water-chestnut", "荸荠", "Water chestnut", "vegetables", "🥕", "root"],
  ["green-beans", "四季豆", "Green beans", "vegetables", "🫛", "pod"],
  ["snow-peas", "荷兰豆", "Snow peas", "vegetables", "🫛", "pod"],
  ["peas", "豌豆", "Peas", "vegetables", "🫛", "pod"],
  ["okra", "秋葵", "Okra", "vegetables", "🫛", "pod"],
  ["asparagus", "芦笋", "Asparagus", "vegetables", "🫛", "pod"],
  ["zucchini", "西葫芦", "Zucchini", "vegetables", "🫛", "pod"],
  ["bitter-melon", "苦瓜", "Bitter melon", "vegetables", "🫛", "pod"],
  ["winter-melon", "冬瓜", "Winter melon", "vegetables", "🫛", "pod"],
  ["loofah", "丝瓜", "Loofah gourd", "vegetables", "🫛", "pod"],
  ["bell-pepper", "彩椒", "Bell pepper", "vegetables", "🫛", "pod"],
  ["bean-sprouts", "豆芽", "Bean sprouts", "vegetables", "🫛", "pod"],
  ["shiitake", "香菇", "Shiitake", "vegetables", "🍄", "mushroom"],
  ["king-oyster-mushroom", "杏鲍菇", "King oyster mushroom", "vegetables", "🍄", "mushroom"],
  ["enoki", "金针菇", "Enoki mushrooms", "vegetables", "🍄", "mushroom"],
  ["wood-ear", "木耳", "Wood ear mushrooms", "vegetables", "🍄", "mushroom"],
  ["snow-fungus", "银耳", "Snow fungus", "vegetables", "🍄", "mushroom"],
  ["lamb", "羊肉", "Lamb", "protein", "🥩", "meat"],
  ["turkey", "火鸡肉", "Turkey", "protein", "🥩", "meat"],
  ["chicken-wings", "鸡翅", "Chicken wings", "protein", "🥩", "meat"],
  ["chicken-liver", "鸡肝", "Chicken liver", "protein", "🥩", "meat"],
  ["pork-ribs", "排骨", "Pork ribs", "protein", "🥩", "meat"],
  ["pork-belly", "五花肉", "Pork belly", "protein", "🥩", "meat"],
  ["ham", "火腿", "Ham", "protein", "🥩", "meat"],
  ["beef-tendon", "牛筋", "Beef tendon", "protein", "🥩", "meat"],
  ["cod", "鳕鱼", "Cod", "protein", "🐟", "fish"],
  ["tuna", "金枪鱼", "Tuna", "protein", "🐟", "fish"],
  ["sea-bass", "鲈鱼", "Sea bass", "protein", "🐟", "fish"],
  ["mackerel", "鲭鱼", "Mackerel", "protein", "🐟", "fish"],
  ["eel", "鳗鱼", "Eel", "protein", "🐟", "fish"],
  ["anchovy", "凤尾鱼", "Anchovies", "protein", "🐟", "fish"],
  ["scallop", "扇贝", "Scallops", "protein", "🦪", "shell"],
  ["mussel", "贻贝", "Mussels", "protein", "🦪", "shell"],
  ["oyster", "牡蛎", "Oysters", "protein", "🦪", "shell"],
  ["lobster", "龙虾", "Lobster", "protein", "🦪", "shell"],
  ["dried-tofu", "豆腐干", "Pressed tofu", "protein", "🫘", "cube"],
  ["tofu-skin", "豆皮", "Tofu skin", "protein", "🫘", "cube"],
  ["tempeh", "天贝", "Tempeh", "protein", "🫘", "cube"],
  ["seitan", "面筋", "Seitan", "protein", "🫘", "cube"],
  ["chickpea", "鹰嘴豆", "Chickpeas", "protein", "🫘", "grain"],
  ["lentil", "扁豆", "Lentils", "protein", "🫘", "grain"],
  ["soybean", "黄豆", "Soybeans", "protein", "🫘", "grain"],
  ["red-bean", "红豆", "Adzuki beans", "protein", "🫘", "grain"],
  ["mung-bean", "绿豆", "Mung beans", "protein", "🫘", "grain"],
  ["peanut", "花生", "Peanuts", "protein", "🫘", "grain"],
  ["glutinous-rice", "糯米", "Glutinous rice", "staples", "🌾", "grain"],
  ["brown-rice", "糙米", "Brown rice", "staples", "🌾", "grain"],
  ["millet", "小米", "Millet", "staples", "🌾", "grain"],
  ["quinoa", "藜麦", "Quinoa", "staples", "🌾", "grain"],
  ["barley", "大麦", "Barley", "staples", "🌾", "grain"],
  ["cornmeal", "玉米面", "Cornmeal", "staples", "🌾", "grain"],
  ["rice-noodles", "米粉", "Rice noodles", "staples", "🌾", "grain"],
  ["vermicelli", "粉丝", "Glass noodles", "staples", "🌾", "grain"],
  ["buckwheat-noodles", "荞麦面", "Soba noodles", "staples", "🌾", "grain"],
  ["breadcrumbs", "面包糠", "Breadcrumbs", "staples", "🌾", "grain"],
  ["dumpling-wrapper", "饺子皮", "Dumpling wrappers", "staples", "🥟", "cube"],
  ["rice-paper", "米纸", "Rice paper", "staples", "🥟", "cube"],
  ["mozzarella", "马苏里拉", "Mozzarella", "dairy", "🧀", "cube"],
  ["parmesan", "帕尔马干酪", "Parmesan", "dairy", "🧀", "cube"],
  ["cream-cheese", "奶油奶酪", "Cream cheese", "dairy", "🧀", "cube"],
  ["peach", "桃子", "Peach", "fruit", "🍑", "fruit"],
  ["pear", "梨", "Pear", "fruit", "🍑", "fruit"],
  ["orange", "橙子", "Orange", "fruit", "🍑", "fruit"],
  ["lime", "青柠", "Lime", "fruit", "🍑", "fruit"],
  ["kiwi", "猕猴桃", "Kiwi", "fruit", "🍑", "fruit"],
  ["grape", "葡萄", "Grapes", "fruit", "🍑", "fruit"],
  ["cherry", "樱桃", "Cherries", "fruit", "🍑", "fruit"],
  ["raspberry", "覆盆子", "Raspberries", "fruit", "🍑", "fruit"],
  ["fig", "无花果", "Fig", "fruit", "🍑", "fruit"],
  ["pomegranate", "石榴", "Pomegranate", "fruit", "🍑", "fruit"],
  ["avocado", "牛油果", "Avocado", "fruit", "🍑", "fruit"],
  ["lychee", "荔枝", "Lychee", "fruit", "🍑", "fruit"],
  ["passion-fruit", "百香果", "Passion fruit", "fruit", "🍑", "fruit"],
  ["papaya", "木瓜", "Papaya", "fruit", "🍑", "fruit"],
  ["light-soy-sauce", "生抽", "Light soy sauce", "seasoning", "🍶", "bottle"],
  ["dark-soy-sauce", "老抽", "Dark soy sauce", "seasoning", "🍶", "bottle"],
  ["oyster-sauce", "蚝油", "Oyster sauce", "seasoning", "🍶", "bottle"],
  ["fish-sauce", "鱼露", "Fish sauce", "seasoning", "🍶", "bottle"],
  ["shaoxing-wine", "绍兴酒", "Shaoxing wine", "seasoning", "🍶", "bottle"],
  ["mirin", "味醂", "Mirin", "seasoning", "🍶", "bottle"],
  ["rice-vinegar", "米醋", "Rice vinegar", "seasoning", "🍶", "bottle"],
  ["balsamic-vinegar", "意大利黑醋", "Balsamic vinegar", "seasoning", "🍶", "bottle"],
  ["sesame-oil", "香油", "Sesame oil", "seasoning", "🍶", "bottle"],
  ["soybean-oil", "大豆油", "Soybean oil", "seasoning", "🍶", "bottle"],
  ["rapeseed-oil", "菜籽油", "Rapeseed oil", "seasoning", "🍶", "bottle"],
  ["peanut-oil", "花生油", "Peanut oil", "seasoning", "🍶", "bottle"],
  ["olive-oil", "橄榄油", "Olive oil", "seasoning", "🍶", "bottle"],
  ["scallion-oil", "葱油", "Scallion oil", "seasoning", "🍶", "bottle"],
  ["lemon-juice", "柠檬汁", "Lemon juice", "seasoning", "🍶", "bottle"],
  ["worcestershire-sauce", "伍斯特酱汁", "Worcestershire sauce", "seasoning", "🍶", "bottle"],
  ["doubanjiang", "郫县豆瓣酱", "Pixian chili bean paste", "seasoning", "🫙", "jar"],
  ["garlic-sauce", "蒜蓉酱", "Garlic sauce", "seasoning", "🫙", "jar"],
  ["chopped-chili-sauce", "剁椒酱", "Chopped chili sauce", "seasoning", "🫙", "jar"],
  ["sweet-bean-sauce", "甜面酱", "Sweet bean sauce", "seasoning", "🫙", "jar"],
  ["hoisin-sauce", "海鲜酱", "Hoisin sauce", "seasoning", "🫙", "jar"],
  ["fermented-black-beans", "豆豉", "Fermented black beans", "seasoning", "🫙", "jar"],
  ["miso", "味噌", "Miso", "seasoning", "🫙", "jar"],
  ["gochujang", "韩式辣椒酱", "Gochujang", "seasoning", "🫙", "jar"],
  ["ketchup", "番茄酱", "Ketchup", "seasoning", "🫙", "jar"],
  ["mayonnaise", "蛋黄酱", "Mayonnaise", "seasoning", "🫙", "jar"],
  ["sesame-paste", "芝麻酱", "Sesame paste", "seasoning", "🫙", "jar"],
  ["peanut-butter", "花生酱", "Peanut butter", "seasoning", "🫙", "jar"],
  ["chili-crisp", "香辣脆油", "Chili crisp", "seasoning", "🫙", "jar"],
  ["pickled-ginger", "泡姜", "Pickled ginger", "seasoning", "🫙", "jar"],
  ["pickled-chili", "泡椒", "Pickled chilies", "seasoning", "🫙", "jar"],
  ["fermented-tofu", "腐乳", "Fermented tofu", "seasoning", "🫙", "jar"],
  ["black-pepper", "黑胡椒", "Black pepper", "seasoning", "🧂", "spice"],
  ["white-pepper", "白胡椒", "White pepper", "seasoning", "🧂", "spice"],
  ["sichuan-pepper", "花椒", "Sichuan peppercorns", "seasoning", "🧂", "spice"],
  ["cumin", "孜然", "Cumin", "seasoning", "🧂", "spice"],
  ["star-anise", "八角", "Star anise", "seasoning", "🧂", "spice"],
  ["cinnamon", "桂皮", "Cinnamon", "seasoning", "🧂", "spice"],
  ["clove", "丁香", "Cloves", "seasoning", "🧂", "spice"],
  ["turmeric", "姜黄", "Turmeric", "seasoning", "🧂", "spice"],
  ["paprika", "红椒粉", "Paprika", "seasoning", "🧂", "spice"],
  ["curry-powder", "咖喱粉", "Curry powder", "seasoning", "🧂", "spice"],
  ["five-spice", "五香粉", "Five-spice powder", "seasoning", "🧂", "spice"],
  ["sesame-seeds", "芝麻", "Sesame seeds", "seasoning", "🧂", "spice"],
  ["nutmeg", "肉豆蔻", "Nutmeg", "seasoning", "🧂", "spice"],
  ["chili-flakes", "辣椒碎", "Chili flakes", "seasoning", "🧂", "spice"],
  ["bay-leaf", "香叶", "Bay leaves", "seasoning", "🌿", "herb"],
  ["basil", "罗勒", "Basil", "seasoning", "🌿", "herb"],
  ["rosemary", "迷迭香", "Rosemary", "seasoning", "🌿", "herb"],
  ["thyme", "百里香", "Thyme", "seasoning", "🌿", "herb"],
  ["oregano", "牛至", "Oregano", "seasoning", "🌿", "herb"],
  ["mint", "薄荷", "Mint", "seasoning", "🌿", "herb"],
  ["cilantro", "香菜", "Cilantro", "seasoning", "🌿", "herb"],
  ["scallion", "香葱", "Scallions", "seasoning", "🌿", "herb"],
  ["garlic", "大蒜", "Garlic", "seasoning", "🧄", "root"],
  ["ginger", "生姜", "Ginger", "seasoning", "🧄", "root"],
  ["shallot", "红葱头", "Shallots", "seasoning", "🧄", "root"],
];
export const ingredients: Ingredient[] = [
  ...originalIngredients,
  ...expandedIngredients.map(([id, name, nameEn, category, emoji, art]): Ingredient => ({
    id, name, nameEn, category, emoji, art, kind: "real",
  })),
];
export const cuisineEnglish: Record<string, string> = {
  全部: "All cuisines",
  中式: "Chinese",
  日式: "Japanese",
  韩式: "Korean",
  意式: "Italian",
  法式: "French",
  东南亚: "Southeast Asian",
  美式: "American",
};
const dishEnglish: Record<string, [string, string]> = {
  "tomato-egg": ["Tomato & eggs", "A bright, comforting taste of home."],
  "mapo-tofu": ["Mapo tofu", "Silky tofu in a warmly tingling chili sauce."],
  kungpao: ["Kung pao chicken", "Tender chicken meets a delightful crunch."],
  "fried-rice": [
    "Golden egg fried rice",
    "A little golden happiness in every grain.",
  ],
  "braised-pork": [
    "Red-braised pork",
    "Rich, savory comfort, gently simmered.",
  ],
  dumpling: [
    "Shrimp dumplings",
    "Little pockets filled with delicious surprises.",
  ],
  sushi: ["Salmon sushi", "Fresh salmon and rice in perfect harmony."],
  ramen: ["Tonkotsu ramen", "A warm bowl for a hungry evening."],
  curry: [
    "Japanese curry rice",
    "Cozy curry beside a little mountain of rice.",
  ],
  omurice: ["Omurice", "A golden egg blanket with a tasty surprise inside."],
  tempura: ["Tempura", "Light, crisp bites of the sea."],
  bibimbap: ["Bibimbap", "Rice, vegetables and spice, happily mixed."],
  kimchi: ["Kimchi tofu soup", "A whole pot of gently spicy comfort."],
  pizza: ["Margherita pizza", "A classic dance of tomato, cheese and basil."],
  carbonara: [
    "Creamy bacon pasta",
    "Rich egg sauce wrapped around every strand.",
  ],
  risotto: [
    "Mushroom risotto",
    "Earthy mushrooms in a creamy, cozy rice dish.",
  ],
  crepe: ["Strawberry crêpe", "A delicate pancake holding a sweet afternoon."],
  "onion-soup": [
    "French onion soup",
    "Caramelized onions beneath bubbling cheese.",
  ],
  croissant: [
    "Butter croissant",
    "Flaky little crescent moons, warm from the oven.",
  ],
  "tom-yum": [
    "Tom yum soup",
    "Bright, fragrant shrimp soup with a spicy spark.",
  ],
  "pad-thai": ["Pad thai", "Sweet, tangy noodles full of street-food charm."],
  burger: ["Cheeseburger", "Juicy beef and melted cheese in one happy bite."],
  pancake: ["Berry pancakes", "Fluffy stacks of pure morning happiness."],
  "mac-cheese": ["Mac & cheese", "Golden, creamy, stretchy comfort."],
};
export const dishes: Dish[] = [
  [
    "tomato-egg",
    "番茄炒蛋",
    "中式",
    "一口酸甜，是最熟悉的家的味道。",
    ["tomato", "egg"],
    "🍅",
    "#F2A483",
  ],
  [
    "mapo-tofu",
    "麻婆豆腐",
    "中式",
    "热辣鲜香，软嫩豆腐裹满红油。",
    ["tofu", "pork", "chili"],
    "🌶️",
    "#E6A088",
  ],
  [
    "kungpao",
    "宫保鸡丁",
    "中式",
    "鲜嫩鸡丁碰上香脆花生。",
    ["chicken", "chili", "onion"],
    "🍗",
    "#E5BC79",
  ],
  [
    "fried-rice",
    "黄金蛋炒饭",
    "中式",
    "每一粒米，都藏着金灿灿的小幸福。",
    ["rice", "egg", "shrimp"],
    "🍚",
    "#F1D886",
  ],
  [
    "braised-pork",
    "红烧肉",
    "中式",
    "慢慢咕嘟出的浓郁酱香。",
    ["pork", "onion"],
    "🥓",
    "#D9A291",
  ],
  [
    "dumpling",
    "鲜虾饺子",
    "中式",
    "白白胖胖的小口袋，装满鲜味。",
    ["shrimp", "pork", "flour"],
    "🥟",
    "#C6DBC0",
  ],
  [
    "sushi",
    "三文鱼寿司",
    "日式",
    "鲜嫩鱼肉与米饭的温柔相遇。",
    ["salmon", "rice"],
    "🍣",
    "#F4B5B8",
  ],
  [
    "ramen",
    "豚骨拉面",
    "日式",
    "热汤与面条，治愈每个饿肚子的夜。",
    ["pork", "noodle", "egg"],
    "🍜",
    "#EDC488",
  ],
  [
    "curry",
    "日式咖喱饭",
    "日式",
    "浓浓咖喱，配一座软糯米饭小山。",
    ["chicken", "potato", "rice", "onion"],
    "🍛",
    "#DCC57E",
  ],
  [
    "omurice",
    "蛋包饭",
    "日式",
    "切开金黄蛋衣，发现热乎乎的惊喜。",
    ["egg", "rice", "tomato"],
    "🍳",
    "#F1D891",
  ],
  [
    "tempura",
    "天妇罗",
    "日式",
    "咔嚓一声，轻盈酥脆的海洋味。",
    ["shrimp", "flour", "mushroom"],
    "🍤",
    "#DFD1B3",
  ],
  [
    "bibimbap",
    "石锅拌饭",
    "韩式",
    "蔬菜、米饭和香辣酱，热闹地拌一起。",
    ["beef", "rice", "egg", "chili"],
    "🥘",
    "#D8C3B1",
  ],
  [
    "kimchi",
    "泡菜豆腐汤",
    "韩式",
    "微辣热汤里，藏着一整锅温暖。",
    ["tofu", "pork", "chili"],
    "🍲",
    "#E5AC98",
  ],
  [
    "pizza",
    "玛格丽特披萨",
    "意式",
    "番茄、芝士与罗勒的经典圆舞曲。",
    ["flour", "tomato", "cheese"],
    "🍕",
    "#E8C88C",
  ],
  [
    "carbonara",
    "奶香培根意面",
    "意式",
    "浓郁蛋酱缠上每一根面条。",
    ["noodle", "egg", "pork", "cheese"],
    "🍝",
    "#EAD7A4",
  ],
  [
    "risotto",
    "蘑菇烩饭",
    "意式",
    "菌菇的香气，在绵密米饭里盛开。",
    ["rice", "mushroom", "butter", "cheese"],
    "🍚",
    "#D0C2B4",
  ],
  [
    "crepe",
    "草莓可丽饼",
    "法式",
    "薄薄饼皮，卷起一整个甜甜的下午。",
    ["flour", "milk", "egg", "strawberry"],
    "🍓",
    "#EEB6C6",
  ],
  [
    "onion-soup",
    "法式洋葱汤",
    "法式",
    "焦糖洋葱与拉丝芝士的暖心魔法。",
    ["onion", "butter", "cheese"],
    "🧅",
    "#D5BF97",
  ],
  [
    "croissant",
    "黄油可颂",
    "法式",
    "层层酥香，像弯弯月亮落在盘子上。",
    ["flour", "butter", "milk"],
    "🥐",
    "#DFC493",
  ],
  [
    "tom-yum",
    "冬阴功汤",
    "东南亚",
    "酸辣鲜虾与香茅，唤醒沉睡的味蕾。",
    ["shrimp", "mushroom", "chili", "coconut"],
    "🦐",
    "#DFACA1",
  ],
  [
    "pad-thai",
    "泰式炒河粉",
    "东南亚",
    "酸甜咸香，藏着街角小摊的烟火气。",
    ["noodle", "shrimp", "egg"],
    "🍜",
    "#D9BB99",
  ],
  [
    "burger",
    "芝士牛肉汉堡",
    "美式",
    "厚实牛肉与融化芝士，一口满足。",
    ["beef", "cheese", "tomato", "flour"],
    "🍔",
    "#D2CA8E",
  ],
  [
    "pancake",
    "莓果松饼",
    "美式",
    "松软叠高高，淋上甜蜜的好心情。",
    ["flour", "milk", "egg", "strawberry"],
    "🥞",
    "#DFAFC3",
  ],
  [
    "mac-cheese",
    "芝士通心粉",
    "美式",
    "金黄、浓郁、拉丝，快乐就是这么简单。",
    ["noodle", "cheese", "milk"],
    "🧀",
    "#E2CF95",
  ],
].map(([id, name, cuisine, description, ingredients, emoji, color]) => ({
  id,
  name,
  cuisine,
  description,
  ingredients,
  emoji,
  color,
  nameEn: dishEnglish[id as string]![0],
  descriptionEn: dishEnglish[id as string]![1],
  cuisineEn: cuisineEnglish[cuisine as string],
  ingredientsEn: (ingredients as string[]).map((id) => ingredientEnglish[id]),
})) as Dish[];
