/** Editable ingredient starting points, not cooking instructions. */
export const combinations = [
  {
    id: "pizza",
    name: "意式披萨",
    nameEn: "Italian pizza",
    emoji: "🍕",
    ingredients: [
      "pizza-base",
      "pizza-sauce",
      "mozzarella",
      "pepperoni",
      "mushroom",
      "bell-pepper",
      "black-olive",
    ],
  },
  {
    id: "fried-chicken",
    name: "香酥炸鸡",
    nameEn: "Crispy fried chicken",
    emoji: "🍗",
    ingredients: [
      "chicken-drumstick",
      "chicken-wings",
      "flour",
      "cornstarch",
      "buttermilk",
      "black-pepper",
      "paprika",
      "salt",
      "peanut-oil",
    ],
  },
  {
    id: "burger",
    name: "芝士牛肉汉堡",
    nameEn: "Cheeseburger",
    emoji: "🍔",
    ingredients: [
      "hamburger-bun",
      "beef",
      "cheese",
      "lettuce",
      "tomato",
      "onion",
      "mustard",
    ],
  },
  {
    id: "sushi",
    name: "三文鱼寿司",
    nameEn: "Salmon sushi",
    emoji: "🍣",
    ingredients: [
      "sushi-rice",
      "salmon",
      "nori",
      "cucumber",
      "avocado",
      "rice-vinegar",
    ],
  },
  {
    id: "taco",
    name: "墨西哥鸡肉卷",
    nameEn: "Chicken tacos",
    emoji: "🌮",
    ingredients: [
      "tortilla",
      "chicken",
      "tomato",
      "lettuce",
      "avocado",
      "lime",
      "cumin",
    ],
  },
  {
    id: "mapo",
    name: "麻婆豆腐",
    nameEn: "Mapo tofu",
    emoji: "🌶️",
    ingredients: [
      "tofu",
      "pork",
      "doubanjiang",
      "sichuan-pepper",
      "garlic",
      "scallion",
    ],
  },
  {
    id: "fried-rice",
    name: "扬州炒饭",
    nameEn: "Yangzhou fried rice",
    emoji: "🍚",
    ingredients: ["rice", "egg", "shrimp", "ham", "peas", "carrot", "scallion"],
  },
  {
    id: "kung-pao",
    name: "宫保鸡丁",
    nameEn: "Kung pao chicken",
    emoji: "🥜",
    ingredients: [
      "chicken",
      "peanut",
      "chili",
      "sichuan-pepper",
      "soy-sauce",
      "vinegar",
      "sugar",
    ],
  },
  {
    id: "curry",
    name: "椰香咖喱",
    nameEn: "Coconut curry",
    emoji: "🍛",
    ingredients: [
      "chicken",
      "potato",
      "carrot",
      "onion",
      "coconut",
      "curry-powder",
      "rice",
    ],
  },
  {
    id: "pasta",
    name: "奶油蘑菇意面",
    nameEn: "Creamy mushroom pasta",
    emoji: "🍝",
    ingredients: [
      "pasta",
      "mushroom",
      "cream",
      "parmesan",
      "garlic",
      "butter",
      "black-pepper",
    ],
  },
  {
    id: "fruit",
    name: "缤纷水果酸奶",
    nameEn: "Fruit yogurt bowl",
    emoji: "🍓",
    ingredients: [
      "yogurt",
      "strawberry",
      "mango",
      "blueberry",
      "banana",
      "oats",
      "honey",
    ],
  },
  {
    id: "kimchi-pizza",
    name: "韩式泡菜披萨",
    nameEn: "Kimchi pizza",
    emoji: "🍕",
    ingredients: [
      "pizza-base",
      "kimchi",
      "mozzarella",
      "bacon",
      "pizza-sauce",
      "scallion",
    ],
  },
  {
    id: "mapo-pasta",
    name: "麻婆意面",
    nameEn: "Mapo pasta",
    emoji: "🍝",
    ingredients: [
      "pasta",
      "tofu",
      "pork",
      "doubanjiang",
      "sichuan-pepper",
      "parmesan",
    ],
  },
  {
    id: "teriyaki-burger",
    name: "照烧鸡腿汉堡",
    nameEn: "Teriyaki chicken burger",
    emoji: "🍔",
    ingredients: [
      "hamburger-bun",
      "chicken-thigh",
      "soy-sauce",
      "mirin",
      "honey",
      "lettuce",
      "mayonnaise",
    ],
  },
  {
    id: "dumpling",
    name: "鲜虾蒸饺",
    nameEn: "Steamed shrimp dumplings",
    emoji: "🥟",
    ingredients: ["dumpling-wrapper", "shrimp", "pork", "ginger", "scallion"],
  },
  {
    id: "hotpot",
    name: "川味小火锅",
    nameEn: "Sichuan hot pot",
    emoji: "🍲",
    ingredients: [
      "beef",
      "tofu",
      "napa-cabbage",
      "mushroom",
      "doubanjiang",
      "sichuan-pepper",
    ],
  },
  {
    id: "roast",
    name: "香草烤鸡",
    nameEn: "Herb roast chicken",
    emoji: "🍗",
    ingredients: [
      "chicken-thigh",
      "potato",
      "rosemary",
      "garlic",
      "olive-oil",
      "lemon",
    ],
  },
  {
    id: "steak",
    name: "黄油煎牛排",
    nameEn: "Butter seared steak",
    emoji: "🥩",
    ingredients: [
      "beef",
      "butter",
      "garlic",
      "thyme",
      "black-pepper",
      "asparagus",
    ],
  },
  {
    id: "waffle",
    name: "莓果华夫饼",
    nameEn: "Berry waffles",
    emoji: "🧇",
    ingredients: [
      "flour",
      "egg",
      "milk",
      "butter",
      "baking-powder",
      "strawberry",
      "honey",
    ],
  },
  {
    id: "tart",
    name: "葡式蛋挞",
    nameEn: "Custard tarts",
    emoji: "🥧",
    ingredients: ["puff-pastry", "egg", "cream", "milk", "sugar"],
  },
  {
    id: "rice-pudding",
    name: "芒果糯米饭",
    nameEn: "Mango sticky rice",
    emoji: "🥭",
    ingredients: [
      "glutinous-rice",
      "mango",
      "coconut",
      "sugar",
      "sesame-seeds",
    ],
  },
  {
    id: "cheese-dumpling",
    name: "芝士泡菜煎饺",
    nameEn: "Cheesy kimchi potstickers",
    emoji: "🥟",
    ingredients: [
      "dumpling-wrapper",
      "kimchi",
      "mozzarella",
      "pork",
      "scallion",
    ],
  },
  {
    id: "mala-taco",
    name: "麻辣牛肉塔可",
    nameEn: "Mala beef tacos",
    emoji: "🌮",
    ingredients: [
      "tortilla",
      "beef",
      "doubanjiang",
      "sichuan-pepper",
      "lettuce",
      "lime",
    ],
  },
  {
    id: "durian-pizza",
    name: "榴莲芝士披萨",
    nameEn: "Durian cheese pizza",
    emoji: "🍕",
    ingredients: ["pizza-base", "durian", "mozzarella", "cream-cheese"],
  },
] as const;
